CREATE SEQUENCE seq_postare
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE seq_comentariu
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE seq_disp
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE seq_top
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE seq_criteriu
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE seq_recenzie
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE TABLE MARCA(
NUME VARCHAR2(15) PRIMARY KEY,
DESCRIERE VARCHAR2(255)
);

CREATE TABLE CATEGORIE(
NUME VARCHAR2(30) PRIMARY KEY,
DESCRIERE VARCHAR2(255)
);

CREATE TABLE DISPOZITIV(
ID_DISPOZITIV NUMBER(5) DEFAULT seq_disp.NEXTVAL PRIMARY KEY,
NUME VARCHAR2(30) NOT NULL,
MARCA VARCHAR2(15),
CATEGORIE VARCHAR2(30),
DIMENSIUNE VARCHAR2(20) NOT NULL,
PROCESOR VARCHAR2(20) NOT NULL,
PLACA_VIDEO VARCHAR2(20) NOT NULL,
CAPACITATE_RAM NUMBER(2) NOT NULL,
CAPACITATE_STOCARE VARCHAR2(10) NOT NULL,
SISTEM_OPERARE VARCHAR2(15) NOT NULL,
CONECTIVITATE VARCHAR2(255) NOT NULL,
PRET_MEDIU NUMBER(5),
FOREIGN KEY (MARCA) REFERENCES MARCA(NUME),
FOREIGN KEY (CATEGORIE) REFERENCES CATEGORIE(NUME)
);

CREATE TABLE TELEFON(
ID_DISPOZITIV NUMBER(5) REFERENCES DISPOZITIV(ID_DISPOZITIV) PRIMARY KEY,
TIP_DISPLAY VARCHAR2(15) NOT NULL,
REZOLUTIE VARCHAR2(10) NOT NULL,
CAMERA_SELFIE VARCHAR2(50),
CAMERE_SPATE VARCHAR2(255),
BATERIE NUMBER(5) NOT NULL
);

CREATE TABLE LAPTOP(
ID_DISPOZITIV NUMBER(5) REFERENCES DISPOZITIV(ID_DISPOZITIV) PRIMARY KEY,
TIP_DISPLAY VARCHAR2(15) NOT NULL,
REZOLUTIE VARCHAR2(10) NOT NULL,
CAMERA VARCHAR2(30),
BATERIE NUMBER(2)
);

CREATE TABLE CALCULATOR(
ID_DISPOZITIV NUMBER(5) REFERENCES DISPOZITIV(ID_DISPOZITIV) PRIMARY KEY,
TIP_CARCASA VARCHAR2(10) NOT NULL,
NR_VENTILATOARE NUMBER(1) NOT NULL,
CAPACITATE_SURSA NUMBER(5) NOT NULL
);

CREATE TABLE UTILIZATOR(
ALIAS VARCHAR2(20) PRIMARY KEY,
PAROLA VARCHAR2(20),
DESCRIERE VARCHAR2(100),
DATA_INSCRIERE DATE DEFAULT SYSDATE,
CHECK (REGEXP_LIKE(PAROLA, '^(?=.*[A/,-Z])(?=.*\d).{8,}$'))
);

CREATE TABLE POSTARE(
ID_POSTARE NUMBER(8) DEFAULT seq_postare.NEXTVAL PRIMARY KEY,
UTILIZATOR VARCHAR2(20) NOT NULL,
TITLU VARCHAR2(20) NOT NULL,
TEXT VARCHAR2(255) NOT NULL,
DATA DATE DEFAULT SYSDATE,
CATEGORIE VARCHAR2(30),
MARCA VARCHAR(15),
DISPOZITIV NUMBER(5),
FOREIGN KEY (UTILIZATOR) REFERENCES UTILIZATOR(ALIAS),
FOREIGN KEY (CATEGORIE) REFERENCES CATEGORIE(NUME),
FOREIGN KEY (MARCA) REFERENCES MARCA(NUME),
FOREIGN KEY (DISPOZITIV) REFERENCES DISPOZITIV(ID_DISPOZITIV),
CHECK (LENGTH(TITLU) >= 5),
CHECK (
            CASE WHEN CATEGORIE IS NOT NULL THEN 1 ELSE 0 END +
            CASE WHEN MARCA IS NOT NULL THEN 1 ELSE 0 END +
            CASE WHEN DISPOZITIV IS NOT NULL THEN 1 ELSE 0 END = 1
        )
);

CREATE TABLE TOP(
ID_TOP NUMBER(3) DEFAULT seq_top.NEXTVAL PRIMARY KEY,
CATEGORIE VARCHAR2(30),
NUME VARCHAR2(50) NOT NULL,
DESCRIERE VARCHAR2(255),
FOREIGN KEY (CATEGORIE) REFERENCES CATEGORIE(NUME)
);

CREATE TABLE CLASEAZA(
ID_TOP NUMBER(3) REFERENCES TOP(ID_TOP) NOT NULL,
ID_DISPOZITIV NUMBER(5) REFERENCES DISPOZITIV(ID_DISPOZITIV) NOT NULL,
LOC NUMBER(2) NOT NULL,
PRIMARY KEY (ID_TOP, ID_DISPOZITIV)
);

CREATE TABLE RECENZIE(
ID_RECENZIE NUMBER(5) PRIMARY KEY,
ID_DISPOZITIV NUMBER(5) NOT NULL,
NOTA NUMBER(3,1),
FOREIGN KEY(ID_DISPOZITIV) REFERENCES DISPOZITIV(ID_DISPOZITIV)
);

CREATE TABLE CRITERIU(
ID_CRITERIU NUMBER(3) PRIMARY KEY,
DESCRIERE VARCHAR2(100)
);

CREATE TABLE PUNCTEAZA(
ID_CRITERIU NUMBER(3) REFERENCES CRITERIU(ID_CRITERIU) NOT NULL,
ID_RECENZIE NUMBER(5) REFERENCES RECENZIE(ID_RECENZIE) NOT NULL,
NOTA NUMBER(3,1) NOT NULL,
ARGUMENTE VARCHAR2(100),
PRIMARY KEY(ID_CRITERIU, ID_RECENZIE)
);

CREATE TABLE COMENTARIU(
ID_COMENTARIU NUMBER(8) DEFAULT seq_comentariu.NEXTVAL PRIMARY KEY,
UTILIZATOR VARCHAR2(20) REFERENCES UTILIZATOR(ALIAS) NOT NULL,
TEXT VARCHAR2(255) NOT NULL,
DATA DATE DEFAULT SYSDATE,
PARITNE_TOP NUMBER(3) REFERENCES TOP(ID_TOP),
PARINTE_POSTARE NUMBER(8) REFERENCES POSTARE(ID_POSTARE),
PARINTE_RECENZIE NUMBER(3) REFERENCES RECENZIE(ID_RECENZIE),
PARINTE_COMENTARIU NUMBER(8) REFERENCES COMENTARIU(ID_COMENTARIU),
CHECK (
            CASE WHEN PARITNE_TOP IS NOT NULL THEN 1 ELSE 0 END +
            CASE WHEN PARINTE_POSTARE IS NOT NULL THEN 1 ELSE 0 END +
            CASE WHEN PARINTE_RECENZIE IS NOT NULL THEN 1 ELSE 0 END +
            CASE WHEN PARINTE_COMENTARIU IS NOT NULL THEN 1 ELSE 0 END = 1
        )
);

CREATE TABLE APRECIAZA(
ID_DISPOZITIV NUMBER(5) REFERENCES DISPOZITIV(ID_DISPOZITIV) NOT NULL,
UTILIZATOR VARCHAR2(20) REFERENCES UTILIZATOR(ALIAS) NOT NULL,
PRIMARY KEY (ID_DISPOZITIV, UTILIZATOR)
);

select * from UTILIZATOR;




